app/clients/__init__.py
from flask.blueprints import Blueprint

clients_blueprint = Blueprint('clients_blueprint', __name__)

from . import views

app/clients/views.py
import json

from flask import render_template, flash, request
from . import clients_blueprint
from ..models import Users
from flask_login import login_required, current_user
from app import db
from .helper_functions import is_client, client_training_sessions,\
  exercise_by_name, training_session_by_id, submit_training_data


@clients_blueprint.before_request
@login_required
@is_client
def before_request():
    if current_user.is_authenticated:
        user = Users.query.filter_by(id=current_user.id).first()

        if user:
            user.seen()

        if user.has_new_training:
            flash('You have a new training! You can check it out in training category!')
            user.has_new_training = False
            db.session.add(user)
            db.session.commit()


@clients_blueprint.route('/clients')
@login_required
@is_client
def profile():
    # tests = Tests.query.filter_by(alone=True).all()
    # users_tests = []
    #
    # if len(current_user.tests) != 0:
    #     users_tests = current_user.tests
    #     users_tests = filter(lambda x: x in tests, users_tests)

    return render_template('clients/profile.html', user=current_user)


@clients_blueprint.route('/clients/training/new_training')
@login_required
@is_client
def new_training():
    return render_template('clients/training/new_training.html', user=current_user)


@clients_blueprint.route('/clients/training/training_history')
@login_required
@is_client
def training_history():
    return render_template('clients/training/training_history.html', user=current_user)


@clients_blueprint.route('/clients/tests')
@login_required
@is_client
def tests():
    return render_template('clients/tests.html', user=current_user)


@clients_blueprint.route('/clients/do_training/')
@login_required
@is_client
def do_training():
    return render_template('clients/training/do_training.html', user=current_user)


@clients_blueprint.route('/clients/statistics/')
@login_required
@is_client
def statistics():
    return render_template('clients/statistics.html', user=current_user)


# ------------------------------ api methods ----------------------------------- #


@clients_blueprint.route('/clients/training_sessions/')
@login_required
@is_client
def get_training_sessions():
    return json.dumps(client_training_sessions(current_user.id, request.args.get('new')))


@clients_blueprint.route('/clients/exercise_by_name/')
@login_required
@is_client
def get_exercise_by_nanm():
    return json.dumps(exercise_by_name(request.args.get('name')))


@clients_blueprint.route('/clients/training_session_by_id/')
@login_required
@is_client
def get_training_session_by_id():
    return json.dumps(training_session_by_id(request.args.get('training_id')))


@clients_blueprint.route('/submit_training', methods=['POST'])
@login_required
def submit_training():
    if submit_training_data(request.json):
        return json.dumps({'status': True})
    return json.dumps({'status': False})

app/templates/clients/client_navbar.html
<nav class="navbar navbar-inverse" style="margin-bottom: 0; border-radius:0;">
  <div class="container-fluid">
     <div class="navbar-header">
       <a class="navbar-brand">
           <span class="glyphicon glyphicon-home" style="color: white"></span>
           <span id="personal-training-diary" style="color: white; font-weight: bold;">PERSONAL TRAINING DIARY</span>
       </a>
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#clients_navbar">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
    </div>
    <div class="collapse navbar-collapse" id="clients_navbar">
        <ul class="nav navbar-nav">
            <li class="active">
                <a href="{{ url_for('clients_blueprint.profile') }}">
                    Welcome, {{ user.first_name }}
                </a>
            </li>
            <li><a href="{{ url_for('clients_blueprint.new_training') }}">TRAINING</a></li>
            <li></li>
            <li><a href="#">PROFILE</a></li>
            <li><a href="{{ url_for('clients_blueprint.statistics') }}">STATISTICS</a></li>
            <li><a href="{{ url_for('clients_blueprint.tests') }}">TESTS</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('auth_blueprint.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
        </ul>
    </div>
  </div>
</nav>

app/templates/clients/profile.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'clients/client_navbar.html' %}
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mine_calendar.css') }}">
{% endblock %}

{% block content %}
    {% include 'flashing_messages.html' %}

    <div class="container" style="margin-top: 2%">
        <div class="row">
            <div class="col-md-3 text-center">
                 <div class="list-group">
                    <a class="list-group-item">First name:  {{ current_user.first_name }}</a>
                    <a class="list-group-item">Last name:  {{ current_user.last_name }}</a>
                    <a class="list-group-item">Weight:  {{ current_user.weight }}kg</a>
                    <a class="list-group-item">Height:  {{ current_user.height }}cm</a>
                </div>
            </div>
            <div class="col-md-6 text-center">
                <div class="message-board">
                    <h4>Message board <span class="glyphicon glyphicon-list-alt"></span></h4>
                    {% if current_user.users_tests == [] %}
                        <hr>
                        <div class="client-message">
                            <div class="client-message-icon">
                                <span class="glyphicon glyphicon-file"></span>
                            </div>
                            <div class="client-message-text">
                                 <h5>Hi, {{ current_user.first_name }}. Welcome to the personal training diary!</h5>
                                 <p>
                                     Before you start with training you should perform some basic tests that you can do by yourself, so you can track progress later on.
                                     You can find them in the tests category. Some of the basic ones you should do are:
                                 </p>
                                 {% for test in tests %}
                                     <ul>
                                        <li>{{ test.test_name }}</li>
                                     </ul>
                                 {% endfor %}
                            </div>
                            <div class="client-message-icon">
                                <span data-toggle="tooltip" title="Dismiss message." class="glyphicon glyphicon-remove remove"></span>
                            </div>
                        </div>
                        <div class="read-more" style="display: none;">
                            <a href="">Read more <span class="glyphicon glyphicon-arrow-right"></span></a>
                        </div>
                        <div class="show-less" style="display: none;">
                            <a href="">Show less <span class="glyphicon glyphicon-arrow-left"></span></a>
                        </div>
                    {% endif %}
                    <hr>
                    {% if users_tests|length != 0 %}
                        <div class="client-message">
                            <div class="client-message-icon">
                                <span class="glyphicon glyphicon-file"></span>
                            </div>
                            <div class="client-message-text">
                                 <h5>There are more tests that you should do!</h5>
                                 <p>
                                     You should do them, it is important to track progress!
                                 </p>
                                 {% for test in users_tests %}
                                     <ul>
                                        <li>{{ test.test_name }}</li>
                                     </ul>
                                 {% endfor %}
                            </div>
                            <div class="client-message-icon">
                                <span data-toggle="tooltip" title="Dismiss message." class="glyphicon glyphicon-remove remove"></span>
                            </div>
                        </div>
                        <div class="read-more" style="display: none;">
                            <a href="">Read more <span class="glyphicon glyphicon-arrow-right"></span></a>
                        </div>
                        <div class="show-less" style="display: none;">
                            <a href="">Show less <span class="glyphicon glyphicon-arrow-left"></span></a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-3 text-center">
                <table id="calendar">
                    <thead>
                        <tr id="month">
                            <th style="text-align: center" colspan="1" ><a id="month_back" href="#">&lt&lt</a></th>
                            <th style="text-align: center" colspan="5" id="selected_month"></th>
                            <th style="text-align: center" colspan="1" ><a id="month_forward" href="#">&gt&gt</a></th>
                        </tr>
                        <tr id="days">
                            <th style="text-align: center; width: 14.2%">Mon</th>
                            <th style="text-align: center; width: 14.2%">Tue</th>
                            <th style="text-align: center; width: 14.2%">Wed</th>
                            <th style="text-align: center; width: 14.2%">Thu</th>
                            <th style="text-align: center; width: 14.2%">Fri</th>
                            <th style="text-align: center; width: 14.2%">Sat</th>
                            <th style="text-align: center; width: 14.2%">Sun</th>
                        </tr>
                    </thead>
                    <tbody id="calendar_body">

                    </tbody>
               </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/mine_calendar.js') }}"></script>
{% endblock %}

app/templates/clients/statistics.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'clients/client_navbar.html' %}
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mine_calendar.css') }}">
{% endblock %}

{% block content %}
    {% include 'flashing_messages.html' %}
    <div id="training-app">
      <statistics user_id="{{ user.id }}"></statistics>
    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/mine_calendar.js') }}"></script>
{% endblock %}

app/templates/clients/tests.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'clients/client_navbar.html' %}
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block content %}
    {% include 'flashing_messages.html' %}
    <div id="training-app">
      <tests :user="{{ user.id }}"></tests>
    </div>

{% endblock %}

{% block scripts %}
  {{ super() }}
{% endblock %}